"""Add frequency_days to Asset

Revision ID: cef7fb777a5f
Revises: 5822348f3a94
Create Date: 2025-08-15 13:51:12.821847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef7fb777a5f'
down_revision = '5822348f3a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('frequency_days')

    # ### end Alembic commands ###
